### PR TITLE
Refactor freight model slightly

### PR DESCRIPTION
**Pull request by zptro**
Move cost calculation inside purpose and make mode-switch. Utilize freight purpose name from specification.

### CODE REVIEW

**Comment by zptro** [comment]
> Nice refactoring! Better utilization of purpose name in contrast to current iteration where it is passed in explicitly.

The `match/case` solution requires Python 3.10 ->, but is this otherwise ready to merge?

**Comment by Konnde** [comment]
> > Nice refactoring! Better utilization of purpose name in contrast to current iteration where it is passed in explicitly.
> 
> The `match/case` solution requires Python 3.10 ->, but is this otherwise ready to merge?

Yes, I have a working 3.7 copy so we can proceed with this one. Then, hopefully at the beginning of the year our enterprise releases us those new Emme licenses, enabling dev continuation here.

**Comment by zptro** [comment]
> > > Nice refactoring! Better utilization of purpose name in contrast to current iteration where it is passed in explicitly.
> > 
> > 
> > The `match/case` solution requires Python 3.10 ->, but is this otherwise ready to merge?
> 
> Yes, I have a working 3.7 copy so we can proceed with this one. Then, hopefully at the beginning of the year our enterprise releases us those new Emme licenses, enabling dev continuation here.

So... approve? 😅

**Review by Konnde — CHANGES_REQUESTED** [review]
Looking good. Added one note.

**Review by Konnde — APPROVED** [review]

**Pull request merged**
