### PR TITLE
Long tours calibration parameters

### PR DESCRIPTION
**Pull request by EliasMarttunen**
Added calibration values to the constants for long tour mode choice.

### CODE REVIEW

**Review by zptro — COMMENTED** [review]
To avoid merge conflicts, you can put them a bit further away, for instance like this under `"mode_choice"`:

```
"calibration": {
  "airplane": {
    "constant": -0.507445531
  },
  "train": {
    "constant": 0.660411049
  },
...
```

**Review by zptro — CHANGES_REQUESTED** [review]
As you can see, there are still conflicts, because you have (by accident?) changed the indentation in the mode choice parameters. Could you change the indentation back to the original, so that we get rid of the merge conflicts?

**Review by zptro — APPROVED** [review]
Looks good!

**Comment by attesn** [comment]
@EliasMarttunen You can merge changes. Probably good to choose "Squash and merge" option.

**Pull request merged**
